# Generated by Django 5.0.2 on 2024-03-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_alter_watchlist_platform_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='active',
        ),
        migrations.RemoveField(
            model_name='review',
            name='update',
        ),
    ]
